// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FabricProtos.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "FabricProtos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* FabricWrapperMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  FabricWrapperMessage_reflection_ = NULL;
struct FabricWrapperMessageOneofInstance {
  const ::HeartbeatMessage* heartbeat_;
  const ::PatternNamesMessage* patternnames_;
  const ::CommandMessage* command_;
  const ::WelcomeMessage* welcome_;
}* FabricWrapperMessage_default_oneof_instance_ = NULL;
const ::google::protobuf::Descriptor* HeartbeatMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  HeartbeatMessage_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* HeartbeatMessage_MemberType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* PatternNamesMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PatternNamesMessage_reflection_ = NULL;
const ::google::protobuf::Descriptor* CommandMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  CommandMessage_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* CommandMessage_CommandList_descriptor_ = NULL;
const ::google::protobuf::Descriptor* WelcomeMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  WelcomeMessage_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_FabricProtos_2eproto() {
  protobuf_AddDesc_FabricProtos_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "FabricProtos.proto");
  GOOGLE_CHECK(file != NULL);
  FabricWrapperMessage_descriptor_ = file->message_type(0);
  static const int FabricWrapperMessage_offsets_[5] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(FabricWrapperMessage_default_oneof_instance_, heartbeat_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(FabricWrapperMessage_default_oneof_instance_, patternnames_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(FabricWrapperMessage_default_oneof_instance_, command_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(FabricWrapperMessage_default_oneof_instance_, welcome_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FabricWrapperMessage, msg_),
  };
  FabricWrapperMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      FabricWrapperMessage_descriptor_,
      FabricWrapperMessage::default_instance_,
      FabricWrapperMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FabricWrapperMessage, _has_bits_[0]),
      -1,
      -1,
      FabricWrapperMessage_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FabricWrapperMessage, _oneof_case_[0]),
      sizeof(FabricWrapperMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(FabricWrapperMessage, _internal_metadata_),
      -1);
  HeartbeatMessage_descriptor_ = file->message_type(1);
  static const int HeartbeatMessage_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, messagetypeid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, versionid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, framelocation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, currentpattern_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, batteryvoltage_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, framerate_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, membertype_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, failedmessages_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, currentpatternname_),
  };
  HeartbeatMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      HeartbeatMessage_descriptor_,
      HeartbeatMessage::default_instance_,
      HeartbeatMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(HeartbeatMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(HeartbeatMessage, _internal_metadata_),
      -1);
  HeartbeatMessage_MemberType_descriptor_ = HeartbeatMessage_descriptor_->enum_type(0);
  PatternNamesMessage_descriptor_ = file->message_type(2);
  static const int PatternNamesMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PatternNamesMessage, name_),
  };
  PatternNamesMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PatternNamesMessage_descriptor_,
      PatternNamesMessage::default_instance_,
      PatternNamesMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PatternNamesMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(PatternNamesMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PatternNamesMessage, _internal_metadata_),
      -1);
  CommandMessage_descriptor_ = file->message_type(3);
  static const int CommandMessage_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandMessage, command_),
  };
  CommandMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      CommandMessage_descriptor_,
      CommandMessage::default_instance_,
      CommandMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(CommandMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CommandMessage, _internal_metadata_),
      -1);
  CommandMessage_CommandList_descriptor_ = CommandMessage_descriptor_->enum_type(0);
  WelcomeMessage_descriptor_ = file->message_type(4);
  static const int WelcomeMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelcomeMessage, buildtime_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelcomeMessage, version_),
  };
  WelcomeMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      WelcomeMessage_descriptor_,
      WelcomeMessage::default_instance_,
      WelcomeMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelcomeMessage, _has_bits_[0]),
      -1,
      -1,
      sizeof(WelcomeMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(WelcomeMessage, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_FabricProtos_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      FabricWrapperMessage_descriptor_, &FabricWrapperMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      HeartbeatMessage_descriptor_, &HeartbeatMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PatternNamesMessage_descriptor_, &PatternNamesMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      CommandMessage_descriptor_, &CommandMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      WelcomeMessage_descriptor_, &WelcomeMessage::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_FabricProtos_2eproto() {
  delete FabricWrapperMessage::default_instance_;
  delete FabricWrapperMessage_default_oneof_instance_;
  delete FabricWrapperMessage_reflection_;
  delete HeartbeatMessage::default_instance_;
  delete HeartbeatMessage_reflection_;
  delete PatternNamesMessage::default_instance_;
  delete PatternNamesMessage_reflection_;
  delete CommandMessage::default_instance_;
  delete CommandMessage_reflection_;
  delete WelcomeMessage::default_instance_;
  delete WelcomeMessage_reflection_;
}

void protobuf_AddDesc_FabricProtos_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\022FabricProtos.proto\"\273\001\n\024FabricWrapperMe"
    "ssage\022&\n\theartbeat\030\001 \001(\0132\021.HeartbeatMess"
    "ageH\000\022,\n\014patternNames\030\002 \001(\0132\024.PatternNam"
    "esMessageH\000\022\"\n\007command\030\003 \001(\0132\017.CommandMe"
    "ssageH\000\022\"\n\007welcome\030\004 \001(\0132\017.WelcomeMessag"
    "eH\000B\005\n\003msg\"\232\003\n\020HeartbeatMessage\022\025\n\rmessa"
    "geTypeID\030\001 \002(\005\022\021\n\tversionID\030\002 \002(\005\022\025\n\rfra"
    "meLocation\030\003 \001(\005\022\026\n\016currentPattern\030\004 \002(\005"
    "\022\026\n\016batteryVoltage\030\005 \001(\005\022\021\n\tframeRate\030\006 "
    "\001(\005\022\022\n\nmemberType\030\007 \002(\005\022\026\n\016failedMessage"
    "s\030\010 \001(\005\022\032\n\022currentPatternName\030\t \002(\t\"\271\001\n\n"
    "MemberType\022\021\n\rPROTOBUF_VEST\020\001\022\020\n\014PROTOBU"
    "F_HAT\020\002\022\022\n\016PROTOBUF_TOWER\020\003\022\030\n\024PROTOBUF_"
    "TOWN_CENTER\020\004\022\026\n\022PROTOBUF_TOWER_EYE\020\005\022\022\n"
    "\016PROTOBUF_DRESS\020\006\022\030\n\024PROTOBUF_WINDFLOWER"
    "S\020\007\022\022\n\016PROTOBUF_REEDS\020\010\"#\n\023PatternNamesM"
    "essage\022\014\n\004name\030\001 \003(\t\"\201\001\n\016CommandMessage\022"
    ",\n\007command\030\001 \002(\0162\033.CommandMessage.Comman"
    "dList\"A\n\013CommandList\022\026\n\022PROTOBUF_HEARTBE"
    "AT\020\001\022\032\n\026PROTOBUF_PATTERN_NAMES\020\002\"4\n\016Welc"
    "omeMessage\022\021\n\tbuildTime\030\001 \002(\t\022\017\n\007version"
    "\030\002 \002(\tB9\n)com._338oaklandcreations.fabri"
    "c.machineryB\014FabricProtos", 905);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FabricProtos.proto", &protobuf_RegisterTypes);
  FabricWrapperMessage::default_instance_ = new FabricWrapperMessage();
  FabricWrapperMessage_default_oneof_instance_ = new FabricWrapperMessageOneofInstance();
  HeartbeatMessage::default_instance_ = new HeartbeatMessage();
  PatternNamesMessage::default_instance_ = new PatternNamesMessage();
  CommandMessage::default_instance_ = new CommandMessage();
  WelcomeMessage::default_instance_ = new WelcomeMessage();
  FabricWrapperMessage::default_instance_->InitAsDefaultInstance();
  HeartbeatMessage::default_instance_->InitAsDefaultInstance();
  PatternNamesMessage::default_instance_->InitAsDefaultInstance();
  CommandMessage::default_instance_->InitAsDefaultInstance();
  WelcomeMessage::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_FabricProtos_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_FabricProtos_2eproto {
  StaticDescriptorInitializer_FabricProtos_2eproto() {
    protobuf_AddDesc_FabricProtos_2eproto();
  }
} static_descriptor_initializer_FabricProtos_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FabricWrapperMessage::kHeartbeatFieldNumber;
const int FabricWrapperMessage::kPatternNamesFieldNumber;
const int FabricWrapperMessage::kCommandFieldNumber;
const int FabricWrapperMessage::kWelcomeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FabricWrapperMessage::FabricWrapperMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:FabricWrapperMessage)
}

void FabricWrapperMessage::InitAsDefaultInstance() {
  FabricWrapperMessage_default_oneof_instance_->heartbeat_ = const_cast< ::HeartbeatMessage*>(&::HeartbeatMessage::default_instance());
  FabricWrapperMessage_default_oneof_instance_->patternnames_ = const_cast< ::PatternNamesMessage*>(&::PatternNamesMessage::default_instance());
  FabricWrapperMessage_default_oneof_instance_->command_ = const_cast< ::CommandMessage*>(&::CommandMessage::default_instance());
  FabricWrapperMessage_default_oneof_instance_->welcome_ = const_cast< ::WelcomeMessage*>(&::WelcomeMessage::default_instance());
}

FabricWrapperMessage::FabricWrapperMessage(const FabricWrapperMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:FabricWrapperMessage)
}

void FabricWrapperMessage::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  clear_has_msg();
}

FabricWrapperMessage::~FabricWrapperMessage() {
  // @@protoc_insertion_point(destructor:FabricWrapperMessage)
  SharedDtor();
}

void FabricWrapperMessage::SharedDtor() {
  if (has_msg()) {
    clear_msg();
  }
  if (this != default_instance_) {
  }
}

void FabricWrapperMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FabricWrapperMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return FabricWrapperMessage_descriptor_;
}

const FabricWrapperMessage& FabricWrapperMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FabricProtos_2eproto();
  return *default_instance_;
}

FabricWrapperMessage* FabricWrapperMessage::default_instance_ = NULL;

FabricWrapperMessage* FabricWrapperMessage::New(::google::protobuf::Arena* arena) const {
  FabricWrapperMessage* n = new FabricWrapperMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FabricWrapperMessage::clear_msg() {
  switch(msg_case()) {
    case kHeartbeat: {
      delete msg_.heartbeat_;
      break;
    }
    case kPatternNames: {
      delete msg_.patternnames_;
      break;
    }
    case kCommand: {
      delete msg_.command_;
      break;
    }
    case kWelcome: {
      delete msg_.welcome_;
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSG_NOT_SET;
}


void FabricWrapperMessage::Clear() {
  clear_msg();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool FabricWrapperMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FabricWrapperMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .HeartbeatMessage heartbeat = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_heartbeat()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_patternNames;
        break;
      }

      // optional .PatternNamesMessage patternNames = 2;
      case 2: {
        if (tag == 18) {
         parse_patternNames:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_patternnames()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_command;
        break;
      }

      // optional .CommandMessage command = 3;
      case 3: {
        if (tag == 26) {
         parse_command:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_command()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_welcome;
        break;
      }

      // optional .WelcomeMessage welcome = 4;
      case 4: {
        if (tag == 34) {
         parse_welcome:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_welcome()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FabricWrapperMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FabricWrapperMessage)
  return false;
#undef DO_
}

void FabricWrapperMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FabricWrapperMessage)
  // optional .HeartbeatMessage heartbeat = 1;
  if (has_heartbeat()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *msg_.heartbeat_, output);
  }

  // optional .PatternNamesMessage patternNames = 2;
  if (has_patternnames()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *msg_.patternnames_, output);
  }

  // optional .CommandMessage command = 3;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *msg_.command_, output);
  }

  // optional .WelcomeMessage welcome = 4;
  if (has_welcome()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *msg_.welcome_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:FabricWrapperMessage)
}

::google::protobuf::uint8* FabricWrapperMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:FabricWrapperMessage)
  // optional .HeartbeatMessage heartbeat = 1;
  if (has_heartbeat()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, *msg_.heartbeat_, target);
  }

  // optional .PatternNamesMessage patternNames = 2;
  if (has_patternnames()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, *msg_.patternnames_, target);
  }

  // optional .CommandMessage command = 3;
  if (has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        3, *msg_.command_, target);
  }

  // optional .WelcomeMessage welcome = 4;
  if (has_welcome()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, *msg_.welcome_, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FabricWrapperMessage)
  return target;
}

int FabricWrapperMessage::ByteSize() const {
  int total_size = 0;

  switch (msg_case()) {
    // optional .HeartbeatMessage heartbeat = 1;
    case kHeartbeat: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.heartbeat_);
      break;
    }
    // optional .PatternNamesMessage patternNames = 2;
    case kPatternNames: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.patternnames_);
      break;
    }
    // optional .CommandMessage command = 3;
    case kCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.command_);
      break;
    }
    // optional .WelcomeMessage welcome = 4;
    case kWelcome: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.welcome_);
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FabricWrapperMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const FabricWrapperMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const FabricWrapperMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void FabricWrapperMessage::MergeFrom(const FabricWrapperMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  switch (from.msg_case()) {
    case kHeartbeat: {
      mutable_heartbeat()->::HeartbeatMessage::MergeFrom(from.heartbeat());
      break;
    }
    case kPatternNames: {
      mutable_patternnames()->::PatternNamesMessage::MergeFrom(from.patternnames());
      break;
    }
    case kCommand: {
      mutable_command()->::CommandMessage::MergeFrom(from.command());
      break;
    }
    case kWelcome: {
      mutable_welcome()->::WelcomeMessage::MergeFrom(from.welcome());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void FabricWrapperMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FabricWrapperMessage::CopyFrom(const FabricWrapperMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FabricWrapperMessage::IsInitialized() const {

  if (has_heartbeat()) {
    if (!this->heartbeat().IsInitialized()) return false;
  }
  if (has_command()) {
    if (!this->command().IsInitialized()) return false;
  }
  if (has_welcome()) {
    if (!this->welcome().IsInitialized()) return false;
  }
  return true;
}

void FabricWrapperMessage::Swap(FabricWrapperMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FabricWrapperMessage::InternalSwap(FabricWrapperMessage* other) {
  std::swap(msg_, other->msg_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FabricWrapperMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = FabricWrapperMessage_descriptor_;
  metadata.reflection = FabricWrapperMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// FabricWrapperMessage

// optional .HeartbeatMessage heartbeat = 1;
bool FabricWrapperMessage::has_heartbeat() const {
  return msg_case() == kHeartbeat;
}
void FabricWrapperMessage::set_has_heartbeat() {
  _oneof_case_[0] = kHeartbeat;
}
void FabricWrapperMessage::clear_heartbeat() {
  if (has_heartbeat()) {
    delete msg_.heartbeat_;
    clear_has_msg();
  }
}
 const ::HeartbeatMessage& FabricWrapperMessage::heartbeat() const {
  // @@protoc_insertion_point(field_get:FabricWrapperMessage.heartbeat)
  return has_heartbeat()
      ? *msg_.heartbeat_
      : ::HeartbeatMessage::default_instance();
}
::HeartbeatMessage* FabricWrapperMessage::mutable_heartbeat() {
  if (!has_heartbeat()) {
    clear_msg();
    set_has_heartbeat();
    msg_.heartbeat_ = new ::HeartbeatMessage;
  }
  // @@protoc_insertion_point(field_mutable:FabricWrapperMessage.heartbeat)
  return msg_.heartbeat_;
}
::HeartbeatMessage* FabricWrapperMessage::release_heartbeat() {
  if (has_heartbeat()) {
    clear_has_msg();
    ::HeartbeatMessage* temp = msg_.heartbeat_;
    msg_.heartbeat_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void FabricWrapperMessage::set_allocated_heartbeat(::HeartbeatMessage* heartbeat) {
  clear_msg();
  if (heartbeat) {
    set_has_heartbeat();
    msg_.heartbeat_ = heartbeat;
  }
  // @@protoc_insertion_point(field_set_allocated:FabricWrapperMessage.heartbeat)
}

// optional .PatternNamesMessage patternNames = 2;
bool FabricWrapperMessage::has_patternnames() const {
  return msg_case() == kPatternNames;
}
void FabricWrapperMessage::set_has_patternnames() {
  _oneof_case_[0] = kPatternNames;
}
void FabricWrapperMessage::clear_patternnames() {
  if (has_patternnames()) {
    delete msg_.patternnames_;
    clear_has_msg();
  }
}
 const ::PatternNamesMessage& FabricWrapperMessage::patternnames() const {
  // @@protoc_insertion_point(field_get:FabricWrapperMessage.patternNames)
  return has_patternnames()
      ? *msg_.patternnames_
      : ::PatternNamesMessage::default_instance();
}
::PatternNamesMessage* FabricWrapperMessage::mutable_patternnames() {
  if (!has_patternnames()) {
    clear_msg();
    set_has_patternnames();
    msg_.patternnames_ = new ::PatternNamesMessage;
  }
  // @@protoc_insertion_point(field_mutable:FabricWrapperMessage.patternNames)
  return msg_.patternnames_;
}
::PatternNamesMessage* FabricWrapperMessage::release_patternnames() {
  if (has_patternnames()) {
    clear_has_msg();
    ::PatternNamesMessage* temp = msg_.patternnames_;
    msg_.patternnames_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void FabricWrapperMessage::set_allocated_patternnames(::PatternNamesMessage* patternnames) {
  clear_msg();
  if (patternnames) {
    set_has_patternnames();
    msg_.patternnames_ = patternnames;
  }
  // @@protoc_insertion_point(field_set_allocated:FabricWrapperMessage.patternNames)
}

// optional .CommandMessage command = 3;
bool FabricWrapperMessage::has_command() const {
  return msg_case() == kCommand;
}
void FabricWrapperMessage::set_has_command() {
  _oneof_case_[0] = kCommand;
}
void FabricWrapperMessage::clear_command() {
  if (has_command()) {
    delete msg_.command_;
    clear_has_msg();
  }
}
 const ::CommandMessage& FabricWrapperMessage::command() const {
  // @@protoc_insertion_point(field_get:FabricWrapperMessage.command)
  return has_command()
      ? *msg_.command_
      : ::CommandMessage::default_instance();
}
::CommandMessage* FabricWrapperMessage::mutable_command() {
  if (!has_command()) {
    clear_msg();
    set_has_command();
    msg_.command_ = new ::CommandMessage;
  }
  // @@protoc_insertion_point(field_mutable:FabricWrapperMessage.command)
  return msg_.command_;
}
::CommandMessage* FabricWrapperMessage::release_command() {
  if (has_command()) {
    clear_has_msg();
    ::CommandMessage* temp = msg_.command_;
    msg_.command_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void FabricWrapperMessage::set_allocated_command(::CommandMessage* command) {
  clear_msg();
  if (command) {
    set_has_command();
    msg_.command_ = command;
  }
  // @@protoc_insertion_point(field_set_allocated:FabricWrapperMessage.command)
}

// optional .WelcomeMessage welcome = 4;
bool FabricWrapperMessage::has_welcome() const {
  return msg_case() == kWelcome;
}
void FabricWrapperMessage::set_has_welcome() {
  _oneof_case_[0] = kWelcome;
}
void FabricWrapperMessage::clear_welcome() {
  if (has_welcome()) {
    delete msg_.welcome_;
    clear_has_msg();
  }
}
 const ::WelcomeMessage& FabricWrapperMessage::welcome() const {
  // @@protoc_insertion_point(field_get:FabricWrapperMessage.welcome)
  return has_welcome()
      ? *msg_.welcome_
      : ::WelcomeMessage::default_instance();
}
::WelcomeMessage* FabricWrapperMessage::mutable_welcome() {
  if (!has_welcome()) {
    clear_msg();
    set_has_welcome();
    msg_.welcome_ = new ::WelcomeMessage;
  }
  // @@protoc_insertion_point(field_mutable:FabricWrapperMessage.welcome)
  return msg_.welcome_;
}
::WelcomeMessage* FabricWrapperMessage::release_welcome() {
  if (has_welcome()) {
    clear_has_msg();
    ::WelcomeMessage* temp = msg_.welcome_;
    msg_.welcome_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
void FabricWrapperMessage::set_allocated_welcome(::WelcomeMessage* welcome) {
  clear_msg();
  if (welcome) {
    set_has_welcome();
    msg_.welcome_ = welcome;
  }
  // @@protoc_insertion_point(field_set_allocated:FabricWrapperMessage.welcome)
}

bool FabricWrapperMessage::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
void FabricWrapperMessage::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
FabricWrapperMessage::MsgCase FabricWrapperMessage::msg_case() const {
  return FabricWrapperMessage::MsgCase(_oneof_case_[0]);
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

const ::google::protobuf::EnumDescriptor* HeartbeatMessage_MemberType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HeartbeatMessage_MemberType_descriptor_;
}
bool HeartbeatMessage_MemberType_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_VEST;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_HAT;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWER;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWN_CENTER;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWER_EYE;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_DRESS;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_WINDFLOWERS;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_REEDS;
const HeartbeatMessage_MemberType HeartbeatMessage::MemberType_MIN;
const HeartbeatMessage_MemberType HeartbeatMessage::MemberType_MAX;
const int HeartbeatMessage::MemberType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HeartbeatMessage::kMessageTypeIDFieldNumber;
const int HeartbeatMessage::kVersionIDFieldNumber;
const int HeartbeatMessage::kFrameLocationFieldNumber;
const int HeartbeatMessage::kCurrentPatternFieldNumber;
const int HeartbeatMessage::kBatteryVoltageFieldNumber;
const int HeartbeatMessage::kFrameRateFieldNumber;
const int HeartbeatMessage::kMemberTypeFieldNumber;
const int HeartbeatMessage::kFailedMessagesFieldNumber;
const int HeartbeatMessage::kCurrentPatternNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HeartbeatMessage::HeartbeatMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:HeartbeatMessage)
}

void HeartbeatMessage::InitAsDefaultInstance() {
}

HeartbeatMessage::HeartbeatMessage(const HeartbeatMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:HeartbeatMessage)
}

void HeartbeatMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  messagetypeid_ = 0;
  versionid_ = 0;
  framelocation_ = 0;
  currentpattern_ = 0;
  batteryvoltage_ = 0;
  framerate_ = 0;
  membertype_ = 0;
  failedmessages_ = 0;
  currentpatternname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

HeartbeatMessage::~HeartbeatMessage() {
  // @@protoc_insertion_point(destructor:HeartbeatMessage)
  SharedDtor();
}

void HeartbeatMessage::SharedDtor() {
  currentpatternname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void HeartbeatMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HeartbeatMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return HeartbeatMessage_descriptor_;
}

const HeartbeatMessage& HeartbeatMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FabricProtos_2eproto();
  return *default_instance_;
}

HeartbeatMessage* HeartbeatMessage::default_instance_ = NULL;

HeartbeatMessage* HeartbeatMessage::New(::google::protobuf::Arena* arena) const {
  HeartbeatMessage* n = new HeartbeatMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HeartbeatMessage::Clear() {
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<HeartbeatMessage*>(16)->f)

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(messagetypeid_, failedmessages_);
  }
  if (has_currentpatternname()) {
    currentpatternname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool HeartbeatMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HeartbeatMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 messageTypeID = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messagetypeid_)));
          set_has_messagetypeid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_versionID;
        break;
      }

      // required int32 versionID = 2;
      case 2: {
        if (tag == 16) {
         parse_versionID:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &versionid_)));
          set_has_versionid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_frameLocation;
        break;
      }

      // optional int32 frameLocation = 3;
      case 3: {
        if (tag == 24) {
         parse_frameLocation:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framelocation_)));
          set_has_framelocation();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_currentPattern;
        break;
      }

      // required int32 currentPattern = 4;
      case 4: {
        if (tag == 32) {
         parse_currentPattern:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &currentpattern_)));
          set_has_currentpattern();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_batteryVoltage;
        break;
      }

      // optional int32 batteryVoltage = 5;
      case 5: {
        if (tag == 40) {
         parse_batteryVoltage:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &batteryvoltage_)));
          set_has_batteryvoltage();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_frameRate;
        break;
      }

      // optional int32 frameRate = 6;
      case 6: {
        if (tag == 48) {
         parse_frameRate:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &framerate_)));
          set_has_framerate();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_memberType;
        break;
      }

      // required int32 memberType = 7;
      case 7: {
        if (tag == 56) {
         parse_memberType:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &membertype_)));
          set_has_membertype();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_failedMessages;
        break;
      }

      // optional int32 failedMessages = 8;
      case 8: {
        if (tag == 64) {
         parse_failedMessages:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &failedmessages_)));
          set_has_failedmessages();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_currentPatternName;
        break;
      }

      // required string currentPatternName = 9;
      case 9: {
        if (tag == 74) {
         parse_currentPatternName:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_currentpatternname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->currentpatternname().data(), this->currentpatternname().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "HeartbeatMessage.currentPatternName");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HeartbeatMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HeartbeatMessage)
  return false;
#undef DO_
}

void HeartbeatMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HeartbeatMessage)
  // required int32 messageTypeID = 1;
  if (has_messagetypeid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messagetypeid(), output);
  }

  // required int32 versionID = 2;
  if (has_versionid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->versionid(), output);
  }

  // optional int32 frameLocation = 3;
  if (has_framelocation()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->framelocation(), output);
  }

  // required int32 currentPattern = 4;
  if (has_currentpattern()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->currentpattern(), output);
  }

  // optional int32 batteryVoltage = 5;
  if (has_batteryvoltage()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->batteryvoltage(), output);
  }

  // optional int32 frameRate = 6;
  if (has_framerate()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->framerate(), output);
  }

  // required int32 memberType = 7;
  if (has_membertype()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->membertype(), output);
  }

  // optional int32 failedMessages = 8;
  if (has_failedmessages()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->failedmessages(), output);
  }

  // required string currentPatternName = 9;
  if (has_currentpatternname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->currentpatternname().data(), this->currentpatternname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "HeartbeatMessage.currentPatternName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->currentpatternname(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:HeartbeatMessage)
}

::google::protobuf::uint8* HeartbeatMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:HeartbeatMessage)
  // required int32 messageTypeID = 1;
  if (has_messagetypeid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messagetypeid(), target);
  }

  // required int32 versionID = 2;
  if (has_versionid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->versionid(), target);
  }

  // optional int32 frameLocation = 3;
  if (has_framelocation()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->framelocation(), target);
  }

  // required int32 currentPattern = 4;
  if (has_currentpattern()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->currentpattern(), target);
  }

  // optional int32 batteryVoltage = 5;
  if (has_batteryvoltage()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->batteryvoltage(), target);
  }

  // optional int32 frameRate = 6;
  if (has_framerate()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->framerate(), target);
  }

  // required int32 memberType = 7;
  if (has_membertype()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->membertype(), target);
  }

  // optional int32 failedMessages = 8;
  if (has_failedmessages()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->failedmessages(), target);
  }

  // required string currentPatternName = 9;
  if (has_currentpatternname()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->currentpatternname().data(), this->currentpatternname().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "HeartbeatMessage.currentPatternName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->currentpatternname(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HeartbeatMessage)
  return target;
}

int HeartbeatMessage::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_messagetypeid()) {
    // required int32 messageTypeID = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messagetypeid());
  }

  if (has_versionid()) {
    // required int32 versionID = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->versionid());
  }

  if (has_currentpattern()) {
    // required int32 currentPattern = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->currentpattern());
  }

  if (has_membertype()) {
    // required int32 memberType = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->membertype());
  }

  if (has_currentpatternname()) {
    // required string currentPatternName = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->currentpatternname());
  }

  return total_size;
}
int HeartbeatMessage::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000014b) ^ 0x0000014b) == 0) {  // All required fields are present.
    // required int32 messageTypeID = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messagetypeid());

    // required int32 versionID = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->versionid());

    // required int32 currentPattern = 4;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->currentpattern());

    // required int32 memberType = 7;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->membertype());

    // required string currentPatternName = 9;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->currentpatternname());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_has_bits_[2 / 32] & 180u) {
    // optional int32 frameLocation = 3;
    if (has_framelocation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->framelocation());
    }

    // optional int32 batteryVoltage = 5;
    if (has_batteryvoltage()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->batteryvoltage());
    }

    // optional int32 frameRate = 6;
    if (has_framerate()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->framerate());
    }

    // optional int32 failedMessages = 8;
    if (has_failedmessages()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->failedmessages());
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HeartbeatMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const HeartbeatMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const HeartbeatMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void HeartbeatMessage::MergeFrom(const HeartbeatMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_messagetypeid()) {
      set_messagetypeid(from.messagetypeid());
    }
    if (from.has_versionid()) {
      set_versionid(from.versionid());
    }
    if (from.has_framelocation()) {
      set_framelocation(from.framelocation());
    }
    if (from.has_currentpattern()) {
      set_currentpattern(from.currentpattern());
    }
    if (from.has_batteryvoltage()) {
      set_batteryvoltage(from.batteryvoltage());
    }
    if (from.has_framerate()) {
      set_framerate(from.framerate());
    }
    if (from.has_membertype()) {
      set_membertype(from.membertype());
    }
    if (from.has_failedmessages()) {
      set_failedmessages(from.failedmessages());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_currentpatternname()) {
      set_has_currentpatternname();
      currentpatternname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.currentpatternname_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void HeartbeatMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeartbeatMessage::CopyFrom(const HeartbeatMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000014b) != 0x0000014b) return false;

  return true;
}

void HeartbeatMessage::Swap(HeartbeatMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HeartbeatMessage::InternalSwap(HeartbeatMessage* other) {
  std::swap(messagetypeid_, other->messagetypeid_);
  std::swap(versionid_, other->versionid_);
  std::swap(framelocation_, other->framelocation_);
  std::swap(currentpattern_, other->currentpattern_);
  std::swap(batteryvoltage_, other->batteryvoltage_);
  std::swap(framerate_, other->framerate_);
  std::swap(membertype_, other->membertype_);
  std::swap(failedmessages_, other->failedmessages_);
  currentpatternname_.Swap(&other->currentpatternname_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HeartbeatMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = HeartbeatMessage_descriptor_;
  metadata.reflection = HeartbeatMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// HeartbeatMessage

// required int32 messageTypeID = 1;
bool HeartbeatMessage::has_messagetypeid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void HeartbeatMessage::set_has_messagetypeid() {
  _has_bits_[0] |= 0x00000001u;
}
void HeartbeatMessage::clear_has_messagetypeid() {
  _has_bits_[0] &= ~0x00000001u;
}
void HeartbeatMessage::clear_messagetypeid() {
  messagetypeid_ = 0;
  clear_has_messagetypeid();
}
 ::google::protobuf::int32 HeartbeatMessage::messagetypeid() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.messageTypeID)
  return messagetypeid_;
}
 void HeartbeatMessage::set_messagetypeid(::google::protobuf::int32 value) {
  set_has_messagetypeid();
  messagetypeid_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.messageTypeID)
}

// required int32 versionID = 2;
bool HeartbeatMessage::has_versionid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void HeartbeatMessage::set_has_versionid() {
  _has_bits_[0] |= 0x00000002u;
}
void HeartbeatMessage::clear_has_versionid() {
  _has_bits_[0] &= ~0x00000002u;
}
void HeartbeatMessage::clear_versionid() {
  versionid_ = 0;
  clear_has_versionid();
}
 ::google::protobuf::int32 HeartbeatMessage::versionid() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.versionID)
  return versionid_;
}
 void HeartbeatMessage::set_versionid(::google::protobuf::int32 value) {
  set_has_versionid();
  versionid_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.versionID)
}

// optional int32 frameLocation = 3;
bool HeartbeatMessage::has_framelocation() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void HeartbeatMessage::set_has_framelocation() {
  _has_bits_[0] |= 0x00000004u;
}
void HeartbeatMessage::clear_has_framelocation() {
  _has_bits_[0] &= ~0x00000004u;
}
void HeartbeatMessage::clear_framelocation() {
  framelocation_ = 0;
  clear_has_framelocation();
}
 ::google::protobuf::int32 HeartbeatMessage::framelocation() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.frameLocation)
  return framelocation_;
}
 void HeartbeatMessage::set_framelocation(::google::protobuf::int32 value) {
  set_has_framelocation();
  framelocation_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.frameLocation)
}

// required int32 currentPattern = 4;
bool HeartbeatMessage::has_currentpattern() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void HeartbeatMessage::set_has_currentpattern() {
  _has_bits_[0] |= 0x00000008u;
}
void HeartbeatMessage::clear_has_currentpattern() {
  _has_bits_[0] &= ~0x00000008u;
}
void HeartbeatMessage::clear_currentpattern() {
  currentpattern_ = 0;
  clear_has_currentpattern();
}
 ::google::protobuf::int32 HeartbeatMessage::currentpattern() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.currentPattern)
  return currentpattern_;
}
 void HeartbeatMessage::set_currentpattern(::google::protobuf::int32 value) {
  set_has_currentpattern();
  currentpattern_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.currentPattern)
}

// optional int32 batteryVoltage = 5;
bool HeartbeatMessage::has_batteryvoltage() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void HeartbeatMessage::set_has_batteryvoltage() {
  _has_bits_[0] |= 0x00000010u;
}
void HeartbeatMessage::clear_has_batteryvoltage() {
  _has_bits_[0] &= ~0x00000010u;
}
void HeartbeatMessage::clear_batteryvoltage() {
  batteryvoltage_ = 0;
  clear_has_batteryvoltage();
}
 ::google::protobuf::int32 HeartbeatMessage::batteryvoltage() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.batteryVoltage)
  return batteryvoltage_;
}
 void HeartbeatMessage::set_batteryvoltage(::google::protobuf::int32 value) {
  set_has_batteryvoltage();
  batteryvoltage_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.batteryVoltage)
}

// optional int32 frameRate = 6;
bool HeartbeatMessage::has_framerate() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void HeartbeatMessage::set_has_framerate() {
  _has_bits_[0] |= 0x00000020u;
}
void HeartbeatMessage::clear_has_framerate() {
  _has_bits_[0] &= ~0x00000020u;
}
void HeartbeatMessage::clear_framerate() {
  framerate_ = 0;
  clear_has_framerate();
}
 ::google::protobuf::int32 HeartbeatMessage::framerate() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.frameRate)
  return framerate_;
}
 void HeartbeatMessage::set_framerate(::google::protobuf::int32 value) {
  set_has_framerate();
  framerate_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.frameRate)
}

// required int32 memberType = 7;
bool HeartbeatMessage::has_membertype() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void HeartbeatMessage::set_has_membertype() {
  _has_bits_[0] |= 0x00000040u;
}
void HeartbeatMessage::clear_has_membertype() {
  _has_bits_[0] &= ~0x00000040u;
}
void HeartbeatMessage::clear_membertype() {
  membertype_ = 0;
  clear_has_membertype();
}
 ::google::protobuf::int32 HeartbeatMessage::membertype() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.memberType)
  return membertype_;
}
 void HeartbeatMessage::set_membertype(::google::protobuf::int32 value) {
  set_has_membertype();
  membertype_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.memberType)
}

// optional int32 failedMessages = 8;
bool HeartbeatMessage::has_failedmessages() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void HeartbeatMessage::set_has_failedmessages() {
  _has_bits_[0] |= 0x00000080u;
}
void HeartbeatMessage::clear_has_failedmessages() {
  _has_bits_[0] &= ~0x00000080u;
}
void HeartbeatMessage::clear_failedmessages() {
  failedmessages_ = 0;
  clear_has_failedmessages();
}
 ::google::protobuf::int32 HeartbeatMessage::failedmessages() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.failedMessages)
  return failedmessages_;
}
 void HeartbeatMessage::set_failedmessages(::google::protobuf::int32 value) {
  set_has_failedmessages();
  failedmessages_ = value;
  // @@protoc_insertion_point(field_set:HeartbeatMessage.failedMessages)
}

// required string currentPatternName = 9;
bool HeartbeatMessage::has_currentpatternname() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void HeartbeatMessage::set_has_currentpatternname() {
  _has_bits_[0] |= 0x00000100u;
}
void HeartbeatMessage::clear_has_currentpatternname() {
  _has_bits_[0] &= ~0x00000100u;
}
void HeartbeatMessage::clear_currentpatternname() {
  currentpatternname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_currentpatternname();
}
 const ::std::string& HeartbeatMessage::currentpatternname() const {
  // @@protoc_insertion_point(field_get:HeartbeatMessage.currentPatternName)
  return currentpatternname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HeartbeatMessage::set_currentpatternname(const ::std::string& value) {
  set_has_currentpatternname();
  currentpatternname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:HeartbeatMessage.currentPatternName)
}
 void HeartbeatMessage::set_currentpatternname(const char* value) {
  set_has_currentpatternname();
  currentpatternname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:HeartbeatMessage.currentPatternName)
}
 void HeartbeatMessage::set_currentpatternname(const char* value, size_t size) {
  set_has_currentpatternname();
  currentpatternname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:HeartbeatMessage.currentPatternName)
}
 ::std::string* HeartbeatMessage::mutable_currentpatternname() {
  set_has_currentpatternname();
  // @@protoc_insertion_point(field_mutable:HeartbeatMessage.currentPatternName)
  return currentpatternname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* HeartbeatMessage::release_currentpatternname() {
  clear_has_currentpatternname();
  return currentpatternname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void HeartbeatMessage::set_allocated_currentpatternname(::std::string* currentpatternname) {
  if (currentpatternname != NULL) {
    set_has_currentpatternname();
  } else {
    clear_has_currentpatternname();
  }
  currentpatternname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), currentpatternname);
  // @@protoc_insertion_point(field_set_allocated:HeartbeatMessage.currentPatternName)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PatternNamesMessage::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PatternNamesMessage::PatternNamesMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PatternNamesMessage)
}

void PatternNamesMessage::InitAsDefaultInstance() {
}

PatternNamesMessage::PatternNamesMessage(const PatternNamesMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PatternNamesMessage)
}

void PatternNamesMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PatternNamesMessage::~PatternNamesMessage() {
  // @@protoc_insertion_point(destructor:PatternNamesMessage)
  SharedDtor();
}

void PatternNamesMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PatternNamesMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PatternNamesMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PatternNamesMessage_descriptor_;
}

const PatternNamesMessage& PatternNamesMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FabricProtos_2eproto();
  return *default_instance_;
}

PatternNamesMessage* PatternNamesMessage::default_instance_ = NULL;

PatternNamesMessage* PatternNamesMessage::New(::google::protobuf::Arena* arena) const {
  PatternNamesMessage* n = new PatternNamesMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PatternNamesMessage::Clear() {
  name_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PatternNamesMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PatternNamesMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (tag == 10) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->name(this->name_size() - 1).data(),
            this->name(this->name_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "PatternNamesMessage.name");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_name;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PatternNamesMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PatternNamesMessage)
  return false;
#undef DO_
}

void PatternNamesMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PatternNamesMessage)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "PatternNamesMessage.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PatternNamesMessage)
}

::google::protobuf::uint8* PatternNamesMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PatternNamesMessage)
  // repeated string name = 1;
  for (int i = 0; i < this->name_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->name(i).data(), this->name(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "PatternNamesMessage.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PatternNamesMessage)
  return target;
}

int PatternNamesMessage::ByteSize() const {
  int total_size = 0;

  // repeated string name = 1;
  total_size += 1 * this->name_size();
  for (int i = 0; i < this->name_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PatternNamesMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PatternNamesMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PatternNamesMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PatternNamesMessage::MergeFrom(const PatternNamesMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  name_.MergeFrom(from.name_);
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PatternNamesMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PatternNamesMessage::CopyFrom(const PatternNamesMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PatternNamesMessage::IsInitialized() const {

  return true;
}

void PatternNamesMessage::Swap(PatternNamesMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PatternNamesMessage::InternalSwap(PatternNamesMessage* other) {
  name_.UnsafeArenaSwap(&other->name_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PatternNamesMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PatternNamesMessage_descriptor_;
  metadata.reflection = PatternNamesMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PatternNamesMessage

// repeated string name = 1;
int PatternNamesMessage::name_size() const {
  return name_.size();
}
void PatternNamesMessage::clear_name() {
  name_.Clear();
}
 const ::std::string& PatternNamesMessage::name(int index) const {
  // @@protoc_insertion_point(field_get:PatternNamesMessage.name)
  return name_.Get(index);
}
 ::std::string* PatternNamesMessage::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:PatternNamesMessage.name)
  return name_.Mutable(index);
}
 void PatternNamesMessage::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:PatternNamesMessage.name)
  name_.Mutable(index)->assign(value);
}
 void PatternNamesMessage::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:PatternNamesMessage.name)
}
 void PatternNamesMessage::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:PatternNamesMessage.name)
}
 ::std::string* PatternNamesMessage::add_name() {
  return name_.Add();
}
 void PatternNamesMessage::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:PatternNamesMessage.name)
}
 void PatternNamesMessage::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:PatternNamesMessage.name)
}
 void PatternNamesMessage::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:PatternNamesMessage.name)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
PatternNamesMessage::name() const {
  // @@protoc_insertion_point(field_list:PatternNamesMessage.name)
  return name_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
PatternNamesMessage::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:PatternNamesMessage.name)
  return &name_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

const ::google::protobuf::EnumDescriptor* CommandMessage_CommandList_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandMessage_CommandList_descriptor_;
}
bool CommandMessage_CommandList_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CommandMessage_CommandList CommandMessage::PROTOBUF_HEARTBEAT;
const CommandMessage_CommandList CommandMessage::PROTOBUF_PATTERN_NAMES;
const CommandMessage_CommandList CommandMessage::CommandList_MIN;
const CommandMessage_CommandList CommandMessage::CommandList_MAX;
const int CommandMessage::CommandList_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandMessage::kCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandMessage::CommandMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommandMessage)
}

void CommandMessage::InitAsDefaultInstance() {
}

CommandMessage::CommandMessage(const CommandMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:CommandMessage)
}

void CommandMessage::SharedCtor() {
  _cached_size_ = 0;
  command_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

CommandMessage::~CommandMessage() {
  // @@protoc_insertion_point(destructor:CommandMessage)
  SharedDtor();
}

void CommandMessage::SharedDtor() {
  if (this != default_instance_) {
  }
}

void CommandMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return CommandMessage_descriptor_;
}

const CommandMessage& CommandMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FabricProtos_2eproto();
  return *default_instance_;
}

CommandMessage* CommandMessage::default_instance_ = NULL;

CommandMessage* CommandMessage::New(::google::protobuf::Arena* arena) const {
  CommandMessage* n = new CommandMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CommandMessage::Clear() {
  command_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool CommandMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommandMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required .CommandMessage.CommandList command = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::CommandMessage_CommandList_IsValid(value)) {
            set_command(static_cast< ::CommandMessage_CommandList >(value));
          } else {
            mutable_unknown_fields()->AddVarint(1, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommandMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommandMessage)
  return false;
#undef DO_
}

void CommandMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommandMessage)
  // required .CommandMessage.CommandList command = 1;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->command(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:CommandMessage)
}

::google::protobuf::uint8* CommandMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:CommandMessage)
  // required .CommandMessage.CommandList command = 1;
  if (has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->command(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommandMessage)
  return target;
}

int CommandMessage::ByteSize() const {
  int total_size = 0;

  // required .CommandMessage.CommandList command = 1;
  if (has_command()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->command());
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const CommandMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const CommandMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void CommandMessage::MergeFrom(const CommandMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_command()) {
      set_command(from.command());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void CommandMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandMessage::CopyFrom(const CommandMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void CommandMessage::Swap(CommandMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommandMessage::InternalSwap(CommandMessage* other) {
  std::swap(command_, other->command_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = CommandMessage_descriptor_;
  metadata.reflection = CommandMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CommandMessage

// required .CommandMessage.CommandList command = 1;
bool CommandMessage::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void CommandMessage::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
void CommandMessage::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
void CommandMessage::clear_command() {
  command_ = 1;
  clear_has_command();
}
 ::CommandMessage_CommandList CommandMessage::command() const {
  // @@protoc_insertion_point(field_get:CommandMessage.command)
  return static_cast< ::CommandMessage_CommandList >(command_);
}
 void CommandMessage::set_command(::CommandMessage_CommandList value) {
  assert(::CommandMessage_CommandList_IsValid(value));
  set_has_command();
  command_ = value;
  // @@protoc_insertion_point(field_set:CommandMessage.command)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WelcomeMessage::kBuildTimeFieldNumber;
const int WelcomeMessage::kVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WelcomeMessage::WelcomeMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:WelcomeMessage)
}

void WelcomeMessage::InitAsDefaultInstance() {
}

WelcomeMessage::WelcomeMessage(const WelcomeMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:WelcomeMessage)
}

void WelcomeMessage::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  buildtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

WelcomeMessage::~WelcomeMessage() {
  // @@protoc_insertion_point(destructor:WelcomeMessage)
  SharedDtor();
}

void WelcomeMessage::SharedDtor() {
  buildtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void WelcomeMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WelcomeMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return WelcomeMessage_descriptor_;
}

const WelcomeMessage& WelcomeMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_FabricProtos_2eproto();
  return *default_instance_;
}

WelcomeMessage* WelcomeMessage::default_instance_ = NULL;

WelcomeMessage* WelcomeMessage::New(::google::protobuf::Arena* arena) const {
  WelcomeMessage* n = new WelcomeMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WelcomeMessage::Clear() {
  if (_has_bits_[0 / 32] & 3u) {
    if (has_buildtime()) {
      buildtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_version()) {
      version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool WelcomeMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:WelcomeMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string buildTime = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_buildtime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->buildtime().data(), this->buildtime().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "WelcomeMessage.buildTime");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_version;
        break;
      }

      // required string version = 2;
      case 2: {
        if (tag == 18) {
         parse_version:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->version().data(), this->version().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "WelcomeMessage.version");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:WelcomeMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:WelcomeMessage)
  return false;
#undef DO_
}

void WelcomeMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:WelcomeMessage)
  // required string buildTime = 1;
  if (has_buildtime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->buildtime().data(), this->buildtime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "WelcomeMessage.buildTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->buildtime(), output);
  }

  // required string version = 2;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "WelcomeMessage.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->version(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:WelcomeMessage)
}

::google::protobuf::uint8* WelcomeMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:WelcomeMessage)
  // required string buildTime = 1;
  if (has_buildtime()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->buildtime().data(), this->buildtime().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "WelcomeMessage.buildTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->buildtime(), target);
  }

  // required string version = 2;
  if (has_version()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->version().data(), this->version().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "WelcomeMessage.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->version(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WelcomeMessage)
  return target;
}

int WelcomeMessage::RequiredFieldsByteSizeFallback() const {
  int total_size = 0;

  if (has_buildtime()) {
    // required string buildTime = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->buildtime());
  }

  if (has_version()) {
    // required string version = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }

  return total_size;
}
int WelcomeMessage::ByteSize() const {
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string buildTime = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->buildtime());

    // required string version = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WelcomeMessage::MergeFrom(const ::google::protobuf::Message& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const WelcomeMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const WelcomeMessage>(
          &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void WelcomeMessage::MergeFrom(const WelcomeMessage& from) {
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_buildtime()) {
      set_has_buildtime();
      buildtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.buildtime_);
    }
    if (from.has_version()) {
      set_has_version();
      version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void WelcomeMessage::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WelcomeMessage::CopyFrom(const WelcomeMessage& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WelcomeMessage::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void WelcomeMessage::Swap(WelcomeMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WelcomeMessage::InternalSwap(WelcomeMessage* other) {
  buildtime_.Swap(&other->buildtime_);
  version_.Swap(&other->version_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WelcomeMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = WelcomeMessage_descriptor_;
  metadata.reflection = WelcomeMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// WelcomeMessage

// required string buildTime = 1;
bool WelcomeMessage::has_buildtime() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void WelcomeMessage::set_has_buildtime() {
  _has_bits_[0] |= 0x00000001u;
}
void WelcomeMessage::clear_has_buildtime() {
  _has_bits_[0] &= ~0x00000001u;
}
void WelcomeMessage::clear_buildtime() {
  buildtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_buildtime();
}
 const ::std::string& WelcomeMessage::buildtime() const {
  // @@protoc_insertion_point(field_get:WelcomeMessage.buildTime)
  return buildtime_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void WelcomeMessage::set_buildtime(const ::std::string& value) {
  set_has_buildtime();
  buildtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:WelcomeMessage.buildTime)
}
 void WelcomeMessage::set_buildtime(const char* value) {
  set_has_buildtime();
  buildtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:WelcomeMessage.buildTime)
}
 void WelcomeMessage::set_buildtime(const char* value, size_t size) {
  set_has_buildtime();
  buildtime_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:WelcomeMessage.buildTime)
}
 ::std::string* WelcomeMessage::mutable_buildtime() {
  set_has_buildtime();
  // @@protoc_insertion_point(field_mutable:WelcomeMessage.buildTime)
  return buildtime_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* WelcomeMessage::release_buildtime() {
  clear_has_buildtime();
  return buildtime_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void WelcomeMessage::set_allocated_buildtime(::std::string* buildtime) {
  if (buildtime != NULL) {
    set_has_buildtime();
  } else {
    clear_has_buildtime();
  }
  buildtime_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), buildtime);
  // @@protoc_insertion_point(field_set_allocated:WelcomeMessage.buildTime)
}

// required string version = 2;
bool WelcomeMessage::has_version() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void WelcomeMessage::set_has_version() {
  _has_bits_[0] |= 0x00000002u;
}
void WelcomeMessage::clear_has_version() {
  _has_bits_[0] &= ~0x00000002u;
}
void WelcomeMessage::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_version();
}
 const ::std::string& WelcomeMessage::version() const {
  // @@protoc_insertion_point(field_get:WelcomeMessage.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void WelcomeMessage::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:WelcomeMessage.version)
}
 void WelcomeMessage::set_version(const char* value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:WelcomeMessage.version)
}
 void WelcomeMessage::set_version(const char* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:WelcomeMessage.version)
}
 ::std::string* WelcomeMessage::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:WelcomeMessage.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* WelcomeMessage::release_version() {
  clear_has_version();
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void WelcomeMessage::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:WelcomeMessage.version)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
