// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FabricProtos.proto

#include "FabricProtos.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
class FabricWrapperMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FabricWrapperMessage>
      _instance;
  const ::HeartbeatMessage* heartbeat_;
  const ::PatternNamesMessage* patternnames_;
  const ::CommandMessage* command_;
  const ::WelcomeMessage* welcome_;
  const ::PatternCommand* patterncommand_;
} _FabricWrapperMessage_default_instance_;
class HeartbeatMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<HeartbeatMessage>
      _instance;
} _HeartbeatMessage_default_instance_;
class PatternNamesMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PatternNamesMessage>
      _instance;
} _PatternNamesMessage_default_instance_;
class PatternCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<PatternCommand>
      _instance;
} _PatternCommand_default_instance_;
class CommandMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CommandMessage>
      _instance;
} _CommandMessage_default_instance_;
class WelcomeMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<WelcomeMessage>
      _instance;
} _WelcomeMessage_default_instance_;
namespace protobuf_FabricProtos_2eproto {
void InitDefaultsFabricWrapperMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  protobuf_FabricProtos_2eproto::InitDefaultsHeartbeatMessage();
  protobuf_FabricProtos_2eproto::InitDefaultsPatternNamesMessage();
  protobuf_FabricProtos_2eproto::InitDefaultsCommandMessage();
  protobuf_FabricProtos_2eproto::InitDefaultsWelcomeMessage();
  protobuf_FabricProtos_2eproto::InitDefaultsPatternCommand();
  {
    void* ptr = &::_FabricWrapperMessage_default_instance_;
    new (ptr) ::FabricWrapperMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::FabricWrapperMessage::InitAsDefaultInstance();
}

void InitDefaultsFabricWrapperMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsFabricWrapperMessageImpl);
}

void InitDefaultsHeartbeatMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  {
    void* ptr = &::_HeartbeatMessage_default_instance_;
    new (ptr) ::HeartbeatMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::HeartbeatMessage::InitAsDefaultInstance();
}

void InitDefaultsHeartbeatMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsHeartbeatMessageImpl);
}

void InitDefaultsPatternNamesMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  {
    void* ptr = &::_PatternNamesMessage_default_instance_;
    new (ptr) ::PatternNamesMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PatternNamesMessage::InitAsDefaultInstance();
}

void InitDefaultsPatternNamesMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPatternNamesMessageImpl);
}

void InitDefaultsPatternCommandImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  {
    void* ptr = &::_PatternCommand_default_instance_;
    new (ptr) ::PatternCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::PatternCommand::InitAsDefaultInstance();
}

void InitDefaultsPatternCommand() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsPatternCommandImpl);
}

void InitDefaultsCommandMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  protobuf_FabricProtos_2eproto::InitDefaultsPatternCommand();
  {
    void* ptr = &::_CommandMessage_default_instance_;
    new (ptr) ::CommandMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::CommandMessage::InitAsDefaultInstance();
}

void InitDefaultsCommandMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsCommandMessageImpl);
}

void InitDefaultsWelcomeMessageImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  {
    void* ptr = &::_WelcomeMessage_default_instance_;
    new (ptr) ::WelcomeMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::WelcomeMessage::InitAsDefaultInstance();
}

void InitDefaultsWelcomeMessage() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsWelcomeMessageImpl);
}

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FabricWrapperMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FabricWrapperMessage, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::FabricWrapperMessageDefaultTypeInternal, heartbeat_),
  offsetof(::FabricWrapperMessageDefaultTypeInternal, patternnames_),
  offsetof(::FabricWrapperMessageDefaultTypeInternal, command_),
  offsetof(::FabricWrapperMessageDefaultTypeInternal, welcome_),
  offsetof(::FabricWrapperMessageDefaultTypeInternal, patterncommand_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::FabricWrapperMessage, msg_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, messagetypeid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, versionid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, currentpattern_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, red_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, green_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, blue_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, speed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, intensity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, membertype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::HeartbeatMessage, currentpatternname_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternNamesMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternNamesMessage, name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, patternnumber_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, speed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, intensity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, red_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, green_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::PatternCommand, blue_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommandMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommandMessage, command_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::CommandMessage, patterncommand_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::WelcomeMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::WelcomeMessage, buildtime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::WelcomeMessage, version_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::FabricWrapperMessage)},
  { 11, -1, sizeof(::HeartbeatMessage)},
  { 26, -1, sizeof(::PatternNamesMessage)},
  { 32, -1, sizeof(::PatternCommand)},
  { 43, -1, sizeof(::CommandMessage)},
  { 50, -1, sizeof(::WelcomeMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_FabricWrapperMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_HeartbeatMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PatternNamesMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_PatternCommand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_CommandMessage_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_WelcomeMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "FabricProtos.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022FabricProtos.proto\"\346\001\n\024FabricWrapperMe"
      "ssage\022&\n\theartbeat\030\001 \001(\0132\021.HeartbeatMess"
      "ageH\000\022,\n\014patternNames\030\002 \001(\0132\024.PatternNam"
      "esMessageH\000\022\"\n\007command\030\003 \001(\0132\017.CommandMe"
      "ssageH\000\022\"\n\007welcome\030\004 \001(\0132\017.WelcomeMessag"
      "eH\000\022)\n\016patternCommand\030\005 \001(\0132\017.PatternCom"
      "mandH\000B\005\n\003msg\"\242\003\n\020HeartbeatMessage\022\025\n\rme"
      "ssageTypeID\030\001 \001(\005\022\021\n\tversionID\030\002 \001(\005\022\026\n\016"
      "currentPattern\030\003 \001(\005\022\013\n\003red\030\004 \001(\005\022\r\n\005gre"
      "en\030\005 \001(\005\022\014\n\004blue\030\006 \001(\005\022\r\n\005speed\030\007 \001(\005\022\021\n"
      "\tintensity\030\010 \001(\005\022\022\n\nmemberType\030\t \001(\005\022\032\n\022"
      "currentPatternName\030\n \001(\t\"\317\001\n\nMemberType\022"
      "\024\n\020PROTOBUF_UNKNOWN\020\000\022\021\n\rPROTOBUF_VEST\020\001"
      "\022\020\n\014PROTOBUF_HAT\020\002\022\022\n\016PROTOBUF_TOWER\020\003\022\030"
      "\n\024PROTOBUF_TOWN_CENTER\020\004\022\026\n\022PROTOBUF_TOW"
      "ER_EYE\020\005\022\022\n\016PROTOBUF_DRESS\020\006\022\030\n\024PROTOBUF"
      "_WINDFLOWERS\020\007\022\022\n\016PROTOBUF_REEDS\020\010\"#\n\023Pa"
      "tternNamesMessage\022\014\n\004name\030\001 \003(\t\"s\n\016Patte"
      "rnCommand\022\025\n\rpatternNumber\030\001 \001(\005\022\r\n\005spee"
      "d\030\002 \001(\005\022\021\n\tintensity\030\003 \001(\005\022\013\n\003red\030\004 \001(\005\022"
      "\r\n\005green\030\005 \001(\005\022\014\n\004blue\030\006 \001(\005\"\200\002\n\016Command"
      "Message\022,\n\007command\030\001 \001(\0162\033.CommandMessag"
      "e.CommandList\022\'\n\016patternCommand\030\002 \001(\0132\017."
      "PatternCommand\"\226\001\n\013CommandList\022\026\n\022PROTOB"
      "UF_HEARTBEAT\020\000\022\032\n\026PROTOBUF_PATTERN_NAMES"
      "\020\001\022\034\n\030PROTOBUF_PATTERN_COMMAND\020\002\022\033\n\027PROT"
      "OBUF_OPC_DISCONNECT\020\003\022\030\n\024PROTOBUF_OPC_CO"
      "NNECT\020\004\"4\n\016WelcomeMessage\022\021\n\tbuildTime\030\001"
      " \001(\t\022\017\n\007version\030\002 \001(\tB9\n)com._338oakland"
      "creations.fabric.machineryB\014FabricProtos"
      "b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1208);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "FabricProtos.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_FabricProtos_2eproto
const ::google::protobuf::EnumDescriptor* HeartbeatMessage_MemberType_descriptor() {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_FabricProtos_2eproto::file_level_enum_descriptors[0];
}
bool HeartbeatMessage_MemberType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_UNKNOWN;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_VEST;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_HAT;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWER;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWN_CENTER;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_TOWER_EYE;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_DRESS;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_WINDFLOWERS;
const HeartbeatMessage_MemberType HeartbeatMessage::PROTOBUF_REEDS;
const HeartbeatMessage_MemberType HeartbeatMessage::MemberType_MIN;
const HeartbeatMessage_MemberType HeartbeatMessage::MemberType_MAX;
const int HeartbeatMessage::MemberType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
const ::google::protobuf::EnumDescriptor* CommandMessage_CommandList_descriptor() {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_FabricProtos_2eproto::file_level_enum_descriptors[1];
}
bool CommandMessage_CommandList_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const CommandMessage_CommandList CommandMessage::PROTOBUF_HEARTBEAT;
const CommandMessage_CommandList CommandMessage::PROTOBUF_PATTERN_NAMES;
const CommandMessage_CommandList CommandMessage::PROTOBUF_PATTERN_COMMAND;
const CommandMessage_CommandList CommandMessage::PROTOBUF_OPC_DISCONNECT;
const CommandMessage_CommandList CommandMessage::PROTOBUF_OPC_CONNECT;
const CommandMessage_CommandList CommandMessage::CommandList_MIN;
const CommandMessage_CommandList CommandMessage::CommandList_MAX;
const int CommandMessage::CommandList_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void FabricWrapperMessage::InitAsDefaultInstance() {
  ::_FabricWrapperMessage_default_instance_.heartbeat_ = const_cast< ::HeartbeatMessage*>(
      ::HeartbeatMessage::internal_default_instance());
  ::_FabricWrapperMessage_default_instance_.patternnames_ = const_cast< ::PatternNamesMessage*>(
      ::PatternNamesMessage::internal_default_instance());
  ::_FabricWrapperMessage_default_instance_.command_ = const_cast< ::CommandMessage*>(
      ::CommandMessage::internal_default_instance());
  ::_FabricWrapperMessage_default_instance_.welcome_ = const_cast< ::WelcomeMessage*>(
      ::WelcomeMessage::internal_default_instance());
  ::_FabricWrapperMessage_default_instance_.patterncommand_ = const_cast< ::PatternCommand*>(
      ::PatternCommand::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FabricWrapperMessage::kHeartbeatFieldNumber;
const int FabricWrapperMessage::kPatternNamesFieldNumber;
const int FabricWrapperMessage::kCommandFieldNumber;
const int FabricWrapperMessage::kWelcomeFieldNumber;
const int FabricWrapperMessage::kPatternCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FabricWrapperMessage::FabricWrapperMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsFabricWrapperMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:FabricWrapperMessage)
}
FabricWrapperMessage::FabricWrapperMessage(const FabricWrapperMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_msg();
  switch (from.msg_case()) {
    case kHeartbeat: {
      mutable_heartbeat()->::HeartbeatMessage::MergeFrom(from.heartbeat());
      break;
    }
    case kPatternNames: {
      mutable_patternnames()->::PatternNamesMessage::MergeFrom(from.patternnames());
      break;
    }
    case kCommand: {
      mutable_command()->::CommandMessage::MergeFrom(from.command());
      break;
    }
    case kWelcome: {
      mutable_welcome()->::WelcomeMessage::MergeFrom(from.welcome());
      break;
    }
    case kPatternCommand: {
      mutable_patterncommand()->::PatternCommand::MergeFrom(from.patterncommand());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:FabricWrapperMessage)
}

void FabricWrapperMessage::SharedCtor() {
  clear_has_msg();
  _cached_size_ = 0;
}

FabricWrapperMessage::~FabricWrapperMessage() {
  // @@protoc_insertion_point(destructor:FabricWrapperMessage)
  SharedDtor();
}

void FabricWrapperMessage::SharedDtor() {
  if (has_msg()) {
    clear_msg();
  }
}

void FabricWrapperMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* FabricWrapperMessage::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FabricWrapperMessage& FabricWrapperMessage::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsFabricWrapperMessage();
  return *internal_default_instance();
}

FabricWrapperMessage* FabricWrapperMessage::New(::google::protobuf::Arena* arena) const {
  FabricWrapperMessage* n = new FabricWrapperMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void FabricWrapperMessage::clear_msg() {
// @@protoc_insertion_point(one_of_clear_start:FabricWrapperMessage)
  switch (msg_case()) {
    case kHeartbeat: {
      delete msg_.heartbeat_;
      break;
    }
    case kPatternNames: {
      delete msg_.patternnames_;
      break;
    }
    case kCommand: {
      delete msg_.command_;
      break;
    }
    case kWelcome: {
      delete msg_.welcome_;
      break;
    }
    case kPatternCommand: {
      delete msg_.patterncommand_;
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = MSG_NOT_SET;
}


void FabricWrapperMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:FabricWrapperMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_msg();
  _internal_metadata_.Clear();
}

bool FabricWrapperMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:FabricWrapperMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .HeartbeatMessage heartbeat = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_heartbeat()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .PatternNamesMessage patternNames = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_patternnames()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .CommandMessage command = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_command()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .WelcomeMessage welcome = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_welcome()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .PatternCommand patternCommand = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_patterncommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:FabricWrapperMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:FabricWrapperMessage)
  return false;
#undef DO_
}

void FabricWrapperMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:FabricWrapperMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HeartbeatMessage heartbeat = 1;
  if (has_heartbeat()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *msg_.heartbeat_, output);
  }

  // .PatternNamesMessage patternNames = 2;
  if (has_patternnames()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *msg_.patternnames_, output);
  }

  // .CommandMessage command = 3;
  if (has_command()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *msg_.command_, output);
  }

  // .WelcomeMessage welcome = 4;
  if (has_welcome()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, *msg_.welcome_, output);
  }

  // .PatternCommand patternCommand = 5;
  if (has_patterncommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, *msg_.patterncommand_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:FabricWrapperMessage)
}

::google::protobuf::uint8* FabricWrapperMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:FabricWrapperMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .HeartbeatMessage heartbeat = 1;
  if (has_heartbeat()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *msg_.heartbeat_, deterministic, target);
  }

  // .PatternNamesMessage patternNames = 2;
  if (has_patternnames()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *msg_.patternnames_, deterministic, target);
  }

  // .CommandMessage command = 3;
  if (has_command()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *msg_.command_, deterministic, target);
  }

  // .WelcomeMessage welcome = 4;
  if (has_welcome()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, *msg_.welcome_, deterministic, target);
  }

  // .PatternCommand patternCommand = 5;
  if (has_patterncommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, *msg_.patterncommand_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FabricWrapperMessage)
  return target;
}

size_t FabricWrapperMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:FabricWrapperMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (msg_case()) {
    // .HeartbeatMessage heartbeat = 1;
    case kHeartbeat: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.heartbeat_);
      break;
    }
    // .PatternNamesMessage patternNames = 2;
    case kPatternNames: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.patternnames_);
      break;
    }
    // .CommandMessage command = 3;
    case kCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.command_);
      break;
    }
    // .WelcomeMessage welcome = 4;
    case kWelcome: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.welcome_);
      break;
    }
    // .PatternCommand patternCommand = 5;
    case kPatternCommand: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *msg_.patterncommand_);
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void FabricWrapperMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:FabricWrapperMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const FabricWrapperMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FabricWrapperMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:FabricWrapperMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:FabricWrapperMessage)
    MergeFrom(*source);
  }
}

void FabricWrapperMessage::MergeFrom(const FabricWrapperMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:FabricWrapperMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.msg_case()) {
    case kHeartbeat: {
      mutable_heartbeat()->::HeartbeatMessage::MergeFrom(from.heartbeat());
      break;
    }
    case kPatternNames: {
      mutable_patternnames()->::PatternNamesMessage::MergeFrom(from.patternnames());
      break;
    }
    case kCommand: {
      mutable_command()->::CommandMessage::MergeFrom(from.command());
      break;
    }
    case kWelcome: {
      mutable_welcome()->::WelcomeMessage::MergeFrom(from.welcome());
      break;
    }
    case kPatternCommand: {
      mutable_patterncommand()->::PatternCommand::MergeFrom(from.patterncommand());
      break;
    }
    case MSG_NOT_SET: {
      break;
    }
  }
}

void FabricWrapperMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:FabricWrapperMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FabricWrapperMessage::CopyFrom(const FabricWrapperMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:FabricWrapperMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FabricWrapperMessage::IsInitialized() const {
  return true;
}

void FabricWrapperMessage::Swap(FabricWrapperMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FabricWrapperMessage::InternalSwap(FabricWrapperMessage* other) {
  using std::swap;
  swap(msg_, other->msg_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata FabricWrapperMessage::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void HeartbeatMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int HeartbeatMessage::kMessageTypeIDFieldNumber;
const int HeartbeatMessage::kVersionIDFieldNumber;
const int HeartbeatMessage::kCurrentPatternFieldNumber;
const int HeartbeatMessage::kRedFieldNumber;
const int HeartbeatMessage::kGreenFieldNumber;
const int HeartbeatMessage::kBlueFieldNumber;
const int HeartbeatMessage::kSpeedFieldNumber;
const int HeartbeatMessage::kIntensityFieldNumber;
const int HeartbeatMessage::kMemberTypeFieldNumber;
const int HeartbeatMessage::kCurrentPatternNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

HeartbeatMessage::HeartbeatMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsHeartbeatMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:HeartbeatMessage)
}
HeartbeatMessage::HeartbeatMessage(const HeartbeatMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  currentpatternname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.currentpatternname().size() > 0) {
    currentpatternname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.currentpatternname_);
  }
  ::memcpy(&messagetypeid_, &from.messagetypeid_,
    static_cast<size_t>(reinterpret_cast<char*>(&membertype_) -
    reinterpret_cast<char*>(&messagetypeid_)) + sizeof(membertype_));
  // @@protoc_insertion_point(copy_constructor:HeartbeatMessage)
}

void HeartbeatMessage::SharedCtor() {
  currentpatternname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&messagetypeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&membertype_) -
      reinterpret_cast<char*>(&messagetypeid_)) + sizeof(membertype_));
  _cached_size_ = 0;
}

HeartbeatMessage::~HeartbeatMessage() {
  // @@protoc_insertion_point(destructor:HeartbeatMessage)
  SharedDtor();
}

void HeartbeatMessage::SharedDtor() {
  currentpatternname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void HeartbeatMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* HeartbeatMessage::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const HeartbeatMessage& HeartbeatMessage::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsHeartbeatMessage();
  return *internal_default_instance();
}

HeartbeatMessage* HeartbeatMessage::New(::google::protobuf::Arena* arena) const {
  HeartbeatMessage* n = new HeartbeatMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void HeartbeatMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:HeartbeatMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  currentpatternname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&messagetypeid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&membertype_) -
      reinterpret_cast<char*>(&messagetypeid_)) + sizeof(membertype_));
  _internal_metadata_.Clear();
}

bool HeartbeatMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:HeartbeatMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 messageTypeID = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &messagetypeid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 versionID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &versionid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 currentPattern = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &currentpattern_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 red = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &red_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 green = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &green_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 blue = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blue_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 speed = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 intensity = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intensity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 memberType = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &membertype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string currentPatternName = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_currentpatternname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->currentpatternname().data(), static_cast<int>(this->currentpatternname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "HeartbeatMessage.currentPatternName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:HeartbeatMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:HeartbeatMessage)
  return false;
#undef DO_
}

void HeartbeatMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:HeartbeatMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 messageTypeID = 1;
  if (this->messagetypeid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->messagetypeid(), output);
  }

  // int32 versionID = 2;
  if (this->versionid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->versionid(), output);
  }

  // int32 currentPattern = 3;
  if (this->currentpattern() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->currentpattern(), output);
  }

  // int32 red = 4;
  if (this->red() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->red(), output);
  }

  // int32 green = 5;
  if (this->green() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->green(), output);
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->blue(), output);
  }

  // int32 speed = 7;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->speed(), output);
  }

  // int32 intensity = 8;
  if (this->intensity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->intensity(), output);
  }

  // int32 memberType = 9;
  if (this->membertype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->membertype(), output);
  }

  // string currentPatternName = 10;
  if (this->currentpatternname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->currentpatternname().data(), static_cast<int>(this->currentpatternname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HeartbeatMessage.currentPatternName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->currentpatternname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:HeartbeatMessage)
}

::google::protobuf::uint8* HeartbeatMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:HeartbeatMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 messageTypeID = 1;
  if (this->messagetypeid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->messagetypeid(), target);
  }

  // int32 versionID = 2;
  if (this->versionid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->versionid(), target);
  }

  // int32 currentPattern = 3;
  if (this->currentpattern() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->currentpattern(), target);
  }

  // int32 red = 4;
  if (this->red() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->red(), target);
  }

  // int32 green = 5;
  if (this->green() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->green(), target);
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->blue(), target);
  }

  // int32 speed = 7;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->speed(), target);
  }

  // int32 intensity = 8;
  if (this->intensity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->intensity(), target);
  }

  // int32 memberType = 9;
  if (this->membertype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->membertype(), target);
  }

  // string currentPatternName = 10;
  if (this->currentpatternname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->currentpatternname().data(), static_cast<int>(this->currentpatternname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "HeartbeatMessage.currentPatternName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->currentpatternname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:HeartbeatMessage)
  return target;
}

size_t HeartbeatMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:HeartbeatMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string currentPatternName = 10;
  if (this->currentpatternname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->currentpatternname());
  }

  // int32 messageTypeID = 1;
  if (this->messagetypeid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->messagetypeid());
  }

  // int32 versionID = 2;
  if (this->versionid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->versionid());
  }

  // int32 currentPattern = 3;
  if (this->currentpattern() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->currentpattern());
  }

  // int32 red = 4;
  if (this->red() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());
  }

  // int32 green = 5;
  if (this->green() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());
  }

  // int32 speed = 7;
  if (this->speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->speed());
  }

  // int32 intensity = 8;
  if (this->intensity() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intensity());
  }

  // int32 memberType = 9;
  if (this->membertype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->membertype());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void HeartbeatMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:HeartbeatMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const HeartbeatMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const HeartbeatMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:HeartbeatMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:HeartbeatMessage)
    MergeFrom(*source);
  }
}

void HeartbeatMessage::MergeFrom(const HeartbeatMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:HeartbeatMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.currentpatternname().size() > 0) {

    currentpatternname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.currentpatternname_);
  }
  if (from.messagetypeid() != 0) {
    set_messagetypeid(from.messagetypeid());
  }
  if (from.versionid() != 0) {
    set_versionid(from.versionid());
  }
  if (from.currentpattern() != 0) {
    set_currentpattern(from.currentpattern());
  }
  if (from.red() != 0) {
    set_red(from.red());
  }
  if (from.green() != 0) {
    set_green(from.green());
  }
  if (from.blue() != 0) {
    set_blue(from.blue());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.intensity() != 0) {
    set_intensity(from.intensity());
  }
  if (from.membertype() != 0) {
    set_membertype(from.membertype());
  }
}

void HeartbeatMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:HeartbeatMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void HeartbeatMessage::CopyFrom(const HeartbeatMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:HeartbeatMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool HeartbeatMessage::IsInitialized() const {
  return true;
}

void HeartbeatMessage::Swap(HeartbeatMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void HeartbeatMessage::InternalSwap(HeartbeatMessage* other) {
  using std::swap;
  currentpatternname_.Swap(&other->currentpatternname_);
  swap(messagetypeid_, other->messagetypeid_);
  swap(versionid_, other->versionid_);
  swap(currentpattern_, other->currentpattern_);
  swap(red_, other->red_);
  swap(green_, other->green_);
  swap(blue_, other->blue_);
  swap(speed_, other->speed_);
  swap(intensity_, other->intensity_);
  swap(membertype_, other->membertype_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata HeartbeatMessage::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PatternNamesMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PatternNamesMessage::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PatternNamesMessage::PatternNamesMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsPatternNamesMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PatternNamesMessage)
}
PatternNamesMessage::PatternNamesMessage(const PatternNamesMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      name_(from.name_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:PatternNamesMessage)
}

void PatternNamesMessage::SharedCtor() {
  _cached_size_ = 0;
}

PatternNamesMessage::~PatternNamesMessage() {
  // @@protoc_insertion_point(destructor:PatternNamesMessage)
  SharedDtor();
}

void PatternNamesMessage::SharedDtor() {
}

void PatternNamesMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PatternNamesMessage::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PatternNamesMessage& PatternNamesMessage::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsPatternNamesMessage();
  return *internal_default_instance();
}

PatternNamesMessage* PatternNamesMessage::New(::google::protobuf::Arena* arena) const {
  PatternNamesMessage* n = new PatternNamesMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PatternNamesMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:PatternNamesMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.Clear();
  _internal_metadata_.Clear();
}

bool PatternNamesMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PatternNamesMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name(this->name_size() - 1).data(),
            static_cast<int>(this->name(this->name_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "PatternNamesMessage.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PatternNamesMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PatternNamesMessage)
  return false;
#undef DO_
}

void PatternNamesMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PatternNamesMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PatternNamesMessage.name");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->name(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PatternNamesMessage)
}

::google::protobuf::uint8* PatternNamesMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PatternNamesMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated string name = 1;
  for (int i = 0, n = this->name_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name(i).data(), static_cast<int>(this->name(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "PatternNamesMessage.name");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->name(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PatternNamesMessage)
  return target;
}

size_t PatternNamesMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PatternNamesMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string name = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->name_size());
  for (int i = 0, n = this->name_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->name(i));
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PatternNamesMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PatternNamesMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const PatternNamesMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PatternNamesMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PatternNamesMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PatternNamesMessage)
    MergeFrom(*source);
  }
}

void PatternNamesMessage::MergeFrom(const PatternNamesMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PatternNamesMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  name_.MergeFrom(from.name_);
}

void PatternNamesMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PatternNamesMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PatternNamesMessage::CopyFrom(const PatternNamesMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PatternNamesMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PatternNamesMessage::IsInitialized() const {
  return true;
}

void PatternNamesMessage::Swap(PatternNamesMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PatternNamesMessage::InternalSwap(PatternNamesMessage* other) {
  using std::swap;
  name_.InternalSwap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PatternNamesMessage::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void PatternCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PatternCommand::kPatternNumberFieldNumber;
const int PatternCommand::kSpeedFieldNumber;
const int PatternCommand::kIntensityFieldNumber;
const int PatternCommand::kRedFieldNumber;
const int PatternCommand::kGreenFieldNumber;
const int PatternCommand::kBlueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PatternCommand::PatternCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsPatternCommand();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:PatternCommand)
}
PatternCommand::PatternCommand(const PatternCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&patternnumber_, &from.patternnumber_,
    static_cast<size_t>(reinterpret_cast<char*>(&blue_) -
    reinterpret_cast<char*>(&patternnumber_)) + sizeof(blue_));
  // @@protoc_insertion_point(copy_constructor:PatternCommand)
}

void PatternCommand::SharedCtor() {
  ::memset(&patternnumber_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blue_) -
      reinterpret_cast<char*>(&patternnumber_)) + sizeof(blue_));
  _cached_size_ = 0;
}

PatternCommand::~PatternCommand() {
  // @@protoc_insertion_point(destructor:PatternCommand)
  SharedDtor();
}

void PatternCommand::SharedDtor() {
}

void PatternCommand::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PatternCommand::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const PatternCommand& PatternCommand::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsPatternCommand();
  return *internal_default_instance();
}

PatternCommand* PatternCommand::New(::google::protobuf::Arena* arena) const {
  PatternCommand* n = new PatternCommand;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PatternCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:PatternCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&patternnumber_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&blue_) -
      reinterpret_cast<char*>(&patternnumber_)) + sizeof(blue_));
  _internal_metadata_.Clear();
}

bool PatternCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PatternCommand)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 patternNumber = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &patternnumber_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 speed = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 intensity = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &intensity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 red = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &red_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 green = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &green_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 blue = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &blue_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PatternCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PatternCommand)
  return false;
#undef DO_
}

void PatternCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PatternCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 patternNumber = 1;
  if (this->patternnumber() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->patternnumber(), output);
  }

  // int32 speed = 2;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->speed(), output);
  }

  // int32 intensity = 3;
  if (this->intensity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->intensity(), output);
  }

  // int32 red = 4;
  if (this->red() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->red(), output);
  }

  // int32 green = 5;
  if (this->green() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->green(), output);
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->blue(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:PatternCommand)
}

::google::protobuf::uint8* PatternCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:PatternCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 patternNumber = 1;
  if (this->patternnumber() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->patternnumber(), target);
  }

  // int32 speed = 2;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->speed(), target);
  }

  // int32 intensity = 3;
  if (this->intensity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->intensity(), target);
  }

  // int32 red = 4;
  if (this->red() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->red(), target);
  }

  // int32 green = 5;
  if (this->green() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->green(), target);
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->blue(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PatternCommand)
  return target;
}

size_t PatternCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:PatternCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 patternNumber = 1;
  if (this->patternnumber() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->patternnumber());
  }

  // int32 speed = 2;
  if (this->speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->speed());
  }

  // int32 intensity = 3;
  if (this->intensity() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->intensity());
  }

  // int32 red = 4;
  if (this->red() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->red());
  }

  // int32 green = 5;
  if (this->green() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->green());
  }

  // int32 blue = 6;
  if (this->blue() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->blue());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PatternCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PatternCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const PatternCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const PatternCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PatternCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PatternCommand)
    MergeFrom(*source);
  }
}

void PatternCommand::MergeFrom(const PatternCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PatternCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.patternnumber() != 0) {
    set_patternnumber(from.patternnumber());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.intensity() != 0) {
    set_intensity(from.intensity());
  }
  if (from.red() != 0) {
    set_red(from.red());
  }
  if (from.green() != 0) {
    set_green(from.green());
  }
  if (from.blue() != 0) {
    set_blue(from.blue());
  }
}

void PatternCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PatternCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PatternCommand::CopyFrom(const PatternCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PatternCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PatternCommand::IsInitialized() const {
  return true;
}

void PatternCommand::Swap(PatternCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PatternCommand::InternalSwap(PatternCommand* other) {
  using std::swap;
  swap(patternnumber_, other->patternnumber_);
  swap(speed_, other->speed_);
  swap(intensity_, other->intensity_);
  swap(red_, other->red_);
  swap(green_, other->green_);
  swap(blue_, other->blue_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PatternCommand::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CommandMessage::InitAsDefaultInstance() {
  ::_CommandMessage_default_instance_._instance.get_mutable()->patterncommand_ = const_cast< ::PatternCommand*>(
      ::PatternCommand::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CommandMessage::kCommandFieldNumber;
const int CommandMessage::kPatternCommandFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CommandMessage::CommandMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsCommandMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:CommandMessage)
}
CommandMessage::CommandMessage(const CommandMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_patterncommand()) {
    patterncommand_ = new ::PatternCommand(*from.patterncommand_);
  } else {
    patterncommand_ = NULL;
  }
  command_ = from.command_;
  // @@protoc_insertion_point(copy_constructor:CommandMessage)
}

void CommandMessage::SharedCtor() {
  ::memset(&patterncommand_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&command_) -
      reinterpret_cast<char*>(&patterncommand_)) + sizeof(command_));
  _cached_size_ = 0;
}

CommandMessage::~CommandMessage() {
  // @@protoc_insertion_point(destructor:CommandMessage)
  SharedDtor();
}

void CommandMessage::SharedDtor() {
  if (this != internal_default_instance()) delete patterncommand_;
}

void CommandMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CommandMessage::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CommandMessage& CommandMessage::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsCommandMessage();
  return *internal_default_instance();
}

CommandMessage* CommandMessage::New(::google::protobuf::Arena* arena) const {
  CommandMessage* n = new CommandMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void CommandMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:CommandMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && patterncommand_ != NULL) {
    delete patterncommand_;
  }
  patterncommand_ = NULL;
  command_ = 0;
  _internal_metadata_.Clear();
}

bool CommandMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:CommandMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .CommandMessage.CommandList command = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_command(static_cast< ::CommandMessage_CommandList >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .PatternCommand patternCommand = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_patterncommand()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:CommandMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:CommandMessage)
  return false;
#undef DO_
}

void CommandMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:CommandMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .CommandMessage.CommandList command = 1;
  if (this->command() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->command(), output);
  }

  // .PatternCommand patternCommand = 2;
  if (this->has_patterncommand()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->patterncommand_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:CommandMessage)
}

::google::protobuf::uint8* CommandMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:CommandMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .CommandMessage.CommandList command = 1;
  if (this->command() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->command(), target);
  }

  // .PatternCommand patternCommand = 2;
  if (this->has_patterncommand()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->patterncommand_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CommandMessage)
  return target;
}

size_t CommandMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:CommandMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .PatternCommand patternCommand = 2;
  if (this->has_patterncommand()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->patterncommand_);
  }

  // .CommandMessage.CommandList command = 1;
  if (this->command() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->command());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CommandMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:CommandMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const CommandMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CommandMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:CommandMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:CommandMessage)
    MergeFrom(*source);
  }
}

void CommandMessage::MergeFrom(const CommandMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:CommandMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_patterncommand()) {
    mutable_patterncommand()->::PatternCommand::MergeFrom(from.patterncommand());
  }
  if (from.command() != 0) {
    set_command(from.command());
  }
}

void CommandMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:CommandMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CommandMessage::CopyFrom(const CommandMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:CommandMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CommandMessage::IsInitialized() const {
  return true;
}

void CommandMessage::Swap(CommandMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CommandMessage::InternalSwap(CommandMessage* other) {
  using std::swap;
  swap(patterncommand_, other->patterncommand_);
  swap(command_, other->command_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CommandMessage::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void WelcomeMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int WelcomeMessage::kBuildTimeFieldNumber;
const int WelcomeMessage::kVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

WelcomeMessage::WelcomeMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_FabricProtos_2eproto::InitDefaultsWelcomeMessage();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:WelcomeMessage)
}
WelcomeMessage::WelcomeMessage(const WelcomeMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  buildtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.buildtime().size() > 0) {
    buildtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.buildtime_);
  }
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.version().size() > 0) {
    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
  // @@protoc_insertion_point(copy_constructor:WelcomeMessage)
}

void WelcomeMessage::SharedCtor() {
  buildtime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

WelcomeMessage::~WelcomeMessage() {
  // @@protoc_insertion_point(destructor:WelcomeMessage)
  SharedDtor();
}

void WelcomeMessage::SharedDtor() {
  buildtime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void WelcomeMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* WelcomeMessage::descriptor() {
  ::protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const WelcomeMessage& WelcomeMessage::default_instance() {
  ::protobuf_FabricProtos_2eproto::InitDefaultsWelcomeMessage();
  return *internal_default_instance();
}

WelcomeMessage* WelcomeMessage::New(::google::protobuf::Arena* arena) const {
  WelcomeMessage* n = new WelcomeMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void WelcomeMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:WelcomeMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  buildtime_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool WelcomeMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:WelcomeMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string buildTime = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_buildtime()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->buildtime().data(), static_cast<int>(this->buildtime().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "WelcomeMessage.buildTime"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string version = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->version().data(), static_cast<int>(this->version().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "WelcomeMessage.version"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:WelcomeMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:WelcomeMessage)
  return false;
#undef DO_
}

void WelcomeMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:WelcomeMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string buildTime = 1;
  if (this->buildtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->buildtime().data(), static_cast<int>(this->buildtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "WelcomeMessage.buildTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->buildtime(), output);
  }

  // string version = 2;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "WelcomeMessage.version");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->version(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:WelcomeMessage)
}

::google::protobuf::uint8* WelcomeMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:WelcomeMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string buildTime = 1;
  if (this->buildtime().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->buildtime().data(), static_cast<int>(this->buildtime().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "WelcomeMessage.buildTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->buildtime(), target);
  }

  // string version = 2;
  if (this->version().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->version().data(), static_cast<int>(this->version().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "WelcomeMessage.version");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->version(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:WelcomeMessage)
  return target;
}

size_t WelcomeMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:WelcomeMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string buildTime = 1;
  if (this->buildtime().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->buildtime());
  }

  // string version = 2;
  if (this->version().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void WelcomeMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:WelcomeMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const WelcomeMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const WelcomeMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:WelcomeMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:WelcomeMessage)
    MergeFrom(*source);
  }
}

void WelcomeMessage::MergeFrom(const WelcomeMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:WelcomeMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.buildtime().size() > 0) {

    buildtime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.buildtime_);
  }
  if (from.version().size() > 0) {

    version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
  }
}

void WelcomeMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:WelcomeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void WelcomeMessage::CopyFrom(const WelcomeMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:WelcomeMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool WelcomeMessage::IsInitialized() const {
  return true;
}

void WelcomeMessage::Swap(WelcomeMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void WelcomeMessage::InternalSwap(WelcomeMessage* other) {
  using std::swap;
  buildtime_.Swap(&other->buildtime_);
  version_.Swap(&other->version_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata WelcomeMessage::GetMetadata() const {
  protobuf_FabricProtos_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_FabricProtos_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
